### ISSUE TITLE
Please add a screen shot for this theme.

### ISSUE THREAD

**Issue by unixorn** [kb10uy/zsh-theme-furry-umbrella#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by kb10uy** [comment]
added.

**Comment by kb10uy** [comment]
Maybe I should modify this... (from plugin to theme)

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/711, thanks!
